name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Node.js v25
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        # Note: Install not supported Python version to test the forced installation of Python 3.13 by uv in `get-platformio.py`
      - name: Install Python 3.12 via uv
        run: uv python install 3.12

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
